---
resources:
  - name: master-src
    type: git
    check_every: 10s
    source:
      uri: 'git@github.com:robCrawford/deepsort-ui.git'
      branch: master
      private_key: ((private_key))
  - name: img-linux
    type: registry-image
    source: {repository: busybox}
jobs:
  - name: build
    public: true
    plan:
      - get: img-linux
      - get: master-src
        trigger: true
      - task: build-html
        image: img-linux
        file: master-src/concourse/tasks/build-html.yml
