---
resources:
  - name: deepsort-src
    type: git
    check_every: 10s
    source:
      uri: 'git@github.com:robCrawford/deepsort-ui.git'
      branch: master
      private_key: ((private_key))
  - name: website-src
    type: git
    check_every: 10s
    source:
      uri: 'git@github.com:robCrawford/robCrawford.github.io.git'
      branch: master
      private_key: ((private_key))
  - name: img-linux
    type: docker-image
    source: {repository: starkandwayne/concourse}
jobs:
  - name: deploy
    public: true
    plan:
      - get: img-linux
      - get: deepsort-src
        trigger: true
      - get: website-src
      - task: deploy-html
        image: img-linux
        file: deepsort-src/concourse/tasks/deploy-html.yml
      - put: website-src
        params:
          repository: updated-website-src
